name: handle-drive
on: [push]
jobs:
  update-test-directory:

    permissions:
      contents: "read"
      id-token: "write"

    runs-on: ubuntu-latest

    steps:
      - name: checkout repo content
        uses: actions/checkout@v3

      - name: check architecture
        run: |
          uname -m
          arch
          gcc -v

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9 #install the python needed
          cache: 'pip'
      - run: pip install -r requirements.txt

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - name: setup gdrive
        run: |
          wget https://github.com/prasmussen/gdrive/releases/download/2.1.1/gdrive_2.1.1_linux_amd64.tar.gz
          mkdir -p $HOME/.local/bin
          tar -zxvf gdrive_2.1.1_linux_amd64.tar.gz -C $HOME/.local/bin
          echo "which gdrive=$(which gdrive)"
          file $(which gdrive)
          mkdir -p ~/.gdrive/
          cp $GOOGLE_APPLICATION_CREDENTIALS ~/.gdrive/credential.json
          ls -l $HOME/.local/bin
          $HOME/.local/bin/gdrive help


      - name: run my script
        run: |
          echo "GITHUB_WORKSPACE=${{ github.workspace }}" >> $GITHUB_ENV
          python ${{ github.workspace }}/scripts/upload_test.py


