name: handle-drive
on: [push]
jobs:
  update-test-directory:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9 #install the python needed
      - name: setup golang
        uses: actions/setup-go@v3 #GOBINのPATHへの追加までやってくれる?
      - run: go version
      - run: echo $PATH
      - name: setup gdrive
        run: |
          go install github.com/prasmussen/gdrive@latest
          gdrive help
