name: handle-drive
on: [push]
jobs:
  update-test-directory:

    permissions:
      contents: "read"
      id-token: "write"

    runs-on: ubuntu-latest

    steps:
      - name: checkout repo content
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9 #install the python needed
          cache: 'pip'
      - run: pip install -r requirements.txt
      - name: setup golang
        uses: actions/setup-go@v3

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - name: setup gdrive
        run: |
          go install github.com/prasmussen/gdrive@latest
          mkdir -p ~/.gdrive/
          cp $GOOGLE_APPLICATION_CREDENTIALS ~/.gdrive/credential.json
          export PATH=$(go env GOPATH)/bin:$PATH
          echo "PATH=$PATH" >> $GITHUB_ENV

      - name: run my script
        run: |
          echo "GITHUB_WORKSPACE=${{ github.workspace }}" >> $GITHUB_ENV
          python ${{ github.workspace }}/scripts/upload_test.py


